spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: root
    password: root
  mail:
    host: smtp.163.com
    username: qxmwrr@163.com
    password: GRDCGOUASMNEBSTH
    default-encoding: UTF-8
    properties.mail.smtp.port: 994
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    
iplimit:
  urls: /api/user/register,/api/user/login
  interval: 60
  limit-req-count: 6
